// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1d5L7eWRGAj2FZ4F5d-yhJvvVndXt9S4',
    appId: '1:862813610442:web:19ebe8645b95f342e3ef33',
    messagingSenderId: '862813610442',
    projectId: 'joul-f22e0',
    authDomain: 'joul-f22e0.firebaseapp.com',
    storageBucket: 'joul-f22e0.firebasestorage.app',
    measurementId: 'G-CL2SF059YN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAryT6QK3TEBTQuHV_RoeQLjoiOKSM51WQ',
    appId: '1:862813610442:android:92a69ca4ec43b686e3ef33',
    messagingSenderId: '862813610442',
    projectId: 'joul-f22e0',
    storageBucket: 'joul-f22e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1ClLIZx3oRTD5YkJ83rbLYbYlxggXZ8E',
    appId: '1:862813610442:ios:bba6cf4d70f9dbf4e3ef33',
    messagingSenderId: '862813610442',
    projectId: 'joul-f22e0',
    storageBucket: 'joul-f22e0.firebasestorage.app',
    iosBundleId: 'com.example.joulV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1ClLIZx3oRTD5YkJ83rbLYbYlxggXZ8E',
    appId: '1:862813610442:ios:bba6cf4d70f9dbf4e3ef33',
    messagingSenderId: '862813610442',
    projectId: 'joul-f22e0',
    storageBucket: 'joul-f22e0.firebasestorage.app',
    iosBundleId: 'com.example.joulV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1d5L7eWRGAj2FZ4F5d-yhJvvVndXt9S4',
    appId: '1:862813610442:web:dde1c5c2565973efe3ef33',
    messagingSenderId: '862813610442',
    projectId: 'joul-f22e0',
    authDomain: 'joul-f22e0.firebaseapp.com',
    storageBucket: 'joul-f22e0.firebasestorage.app',
    measurementId: 'G-ZXLFX1DGH1',
  );
}
